# Generated by Django 5.1.5 on 2026-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_more_sample_fleets'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetphonebinding',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('operator', 'Operator'), ('admin', 'Admin'), ('owner', 'Owner')], default='driver', max_length=20),
        ),
    ]
