# Generated by Django 5.1.5 on 2026-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_newtech_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincodechallenge',
            name='provider',
            field=models.CharField(default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='logincodechallenge',
            name='provider_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
