# Generated by Django 5.1.5 on 2026-04-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_sample_fleets'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincodechallenge',
            name='requested_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
