# Generated by Django 5.1.5 on 2026-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logincodechallenge_requested_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fleetphonebinding',
            unique_together={('fleet', 'phone_number', 'role')},
        ),
    ]
