# Generated by Django 5.1.5 on 2026-04-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_fleetphonebinding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfleetmembership',
            name='last_yandex_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverfleetmembership',
            name='yandex_balance_currency',
            field=models.CharField(default='GEL', max_length=8),
        ),
        migrations.AddField(
            model_name='driverfleetmembership',
            name='yandex_current_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='driverfleetmembership',
            name='yandex_display_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='driverfleetmembership',
            name='yandex_phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='driverfleetmembership',
            name='yandex_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
