# Generated by Django 5.1.5 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_driverfleetmembership_last_yandex_sync_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="bog_source_account_number",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
