# Generated by Django 5.1.5 on 2026-03-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_bankaccount_beneficiary_inn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='bog', max_length=32)),
                ('provider_transaction_id', models.CharField(max_length=120, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='GEL', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_text', models.TextField(blank=True)),
                ('payer_name', models.CharField(blank=True, max_length=140)),
                ('payer_inn', models.CharField(blank=True, max_length=32)),
                ('payer_account_number', models.CharField(blank=True, max_length=64)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ignored', 'Ignored')], default='unmatched', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_bank_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GEL', max_length=8)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('reference_code', models.CharField(max_length=32)),
                ('provider', models.CharField(default='bog', max_length=32)),
                ('provider_transaction_id', models.CharField(max_length=120, unique=True)),
                ('payer_name', models.CharField(blank=True, max_length=140)),
                ('payer_inn', models.CharField(blank=True, max_length=32)),
                ('payer_account_number', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallet.wallet')),
                ('incoming_transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit', to='wallet.incomingbanktransfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
