# Generated by Django 5.1.5 on 2026-02-21 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yandex', 'Yandex'), ('bank_sim', 'Bank Simulator')], max_length=20)),
                ('external_account_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'external_account_id')},
            },
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.providerconnection')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('connection', 'external_id')},
            },
        ),
    ]
