# Generated by Django 5.1.5 on 2026-02-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('wallet', '0002_bankaccount_transaction_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSimulatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payout_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('settled', 'Settled'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='accepted', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payouts', to='integrations.providerconnection')),
                ('withdrawal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_simulator_payout', to='wallet.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
