# Generated by Django 5.1.5 on 2026-03-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_banksimulatorpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexDriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_driver_id', models.CharField(max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_driver_profiles', to='integrations.providerconnection')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('connection', 'external_driver_id')},
            },
        ),
        migrations.CreateModel(
            name='YandexTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_transaction_id', models.CharField(max_length=120)),
                ('driver_external_id', models.CharField(blank=True, max_length=120)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(default='GEL', max_length=8)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('direction', models.CharField(blank=True, max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_transactions', to='integrations.providerconnection')),
                ('external_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_transaction_record', to='integrations.externalevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('connection', 'external_transaction_id')},
            },
        ),
    ]
