# Generated by Django 5.1.5 on 2026-03-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_yandexdriverprofile_yandextransactionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('api', 'API'), ('scheduler', 'Scheduler')], default='api', max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('error', 'Error')], default='error', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('full_sync', models.BooleanField(default=False)),
                ('drivers_http_status', models.IntegerField(blank=True, null=True)),
                ('transactions_http_status', models.IntegerField(blank=True, null=True)),
                ('drivers_fetched', models.IntegerField(default=0)),
                ('drivers_upserted', models.IntegerField(default=0)),
                ('transactions_fetched', models.IntegerField(default=0)),
                ('transactions_stored_new', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('imported_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cursor_from', models.DateTimeField(blank=True, null=True)),
                ('cursor_to', models.DateTimeField(blank=True, null=True)),
                ('cursor_next_from', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_sync_runs', to='integrations.providerconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YandexTransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_category_id', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('is_creatable', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_categories', to='integrations.providerconnection')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('connection', 'external_category_id')},
            },
        ),
    ]
