# Generated by Django 5.1.5 on 2026-03-17 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_bogpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerconnection',
            name='provider',
            field=models.CharField(choices=[('yandex', 'Yandex'), ('bog', 'Bank of Georgia'), ('bog_payments', 'BoG Payments'), ('bank_sim', 'Bank Simulator')], max_length=20),
        ),
        migrations.CreateModel(
            name='BogCardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_order_id', models.CharField(max_length=120, unique=True)),
                ('external_order_id', models.CharField(db_index=True, max_length=120)),
                ('parent_order_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GEL', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('provider_order_status', models.CharField(blank=True, max_length=80)),
                ('redirect_url', models.TextField(blank=True)),
                ('details_url', models.TextField(blank=True)),
                ('callback_url', models.TextField(blank=True)),
                ('success_url', models.TextField(blank=True)),
                ('fail_url', models.TextField(blank=True)),
                ('save_card', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('payer_identifier', models.CharField(blank=True, max_length=64)),
                ('transfer_method', models.CharField(blank=True, max_length=32)),
                ('card_type', models.CharField(blank=True, max_length=32)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('latest_details', models.JSONField(blank=True, default=dict)),
                ('latest_callback', models.JSONField(blank=True, default=dict)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bog_card_orders', to='integrations.providerconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bog_card_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
