# Generated by Django 5.1.5 on 2026-04-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_driverfleetmembership_last_yandex_sync_at_and_more'),
        ('integrations', '0007_bogcardorder_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconnection',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='accounts.fleet'),
        ),
    ]
