from django.urls import path

from .views import (
    ConnectBankSimulatorView,
    ConnectYandexView,
    ImportYandexEventsView,
    ListBogPayoutsView,
    ListBankSimulatorPayoutsView,
    ListYandexCategoriesView,
    ListYandexDriverSummariesView,
    ListYandexDriversView,
    ListYandexEventsView,
    ListYandexSyncRunsView,
    ListYandexTransactionsView,
    PurgeSimulatedYandexDataView,
    ReconcileYandexView,
    ReconciliationSummaryView,
    SimulateYandexEventsView,
    SyncYandexCategoriesView,
    SyncLiveYandexView,
    SubmitBankSimulatorPayoutView,
    SubmitBogPayoutView,
    SyncAllBogPayoutStatusesView,
    SyncBogPayoutStatusView,
    TestBogTokenConnectionView,
    TestYandexConnectionView,
    UpdateBankSimulatorPayoutStatusView,
    YandexDriverDetailView,
)


urlpatterns = [
    path("yandex/connect/", ConnectYandexView.as_view(), name="yandex-connect"),
    path("yandex/test-connection/", TestYandexConnectionView.as_view(), name="yandex-test-connection"),
    path("yandex/sync-live/", SyncLiveYandexView.as_view(), name="yandex-sync-live"),
    path("yandex/sync-categories/", SyncYandexCategoriesView.as_view(), name="yandex-sync-categories"),
    path("yandex/categories/", ListYandexCategoriesView.as_view(), name="yandex-categories"),
    path("yandex/drivers/", ListYandexDriversView.as_view(), name="yandex-drivers"),
    path("yandex/driver-summaries/", ListYandexDriverSummariesView.as_view(), name="yandex-driver-summaries"),
    path("yandex/drivers/<str:external_driver_id>/", YandexDriverDetailView.as_view(), name="yandex-driver-detail"),
    path("yandex/transactions/", ListYandexTransactionsView.as_view(), name="yandex-transactions"),
    path("yandex/sync-runs/", ListYandexSyncRunsView.as_view(), name="yandex-sync-runs"),
    path("yandex/events/", ListYandexEventsView.as_view(), name="yandex-events"),
    path("yandex/simulate-events/", SimulateYandexEventsView.as_view(), name="yandex-simulate"),
    path("yandex/import/", ImportYandexEventsView.as_view(), name="yandex-import"),
    path("yandex/reconcile/", ReconcileYandexView.as_view(), name="yandex-reconcile"),
    path("yandex/purge-simulated/", PurgeSimulatedYandexDataView.as_view(), name="yandex-purge-simulated"),
    path("bog/test-token/", TestBogTokenConnectionView.as_view(), name="bog-test-token"),
    path("bog/payouts/", ListBogPayoutsView.as_view(), name="bog-payouts"),
    path("bog/payouts/submit/", SubmitBogPayoutView.as_view(), name="bog-submit"),
    path("bog/payouts/sync-all/", SyncAllBogPayoutStatusesView.as_view(), name="bog-sync-all"),
    path("bog/payouts/<int:payout_id>/status/", SyncBogPayoutStatusView.as_view(), name="bog-status-sync"),
    path("bank-sim/connect/", ConnectBankSimulatorView.as_view(), name="bank-sim-connect"),
    path("bank-sim/payouts/", ListBankSimulatorPayoutsView.as_view(), name="bank-sim-payouts"),
    path("bank-sim/payouts/submit/", SubmitBankSimulatorPayoutView.as_view(), name="bank-sim-submit"),
    path(
        "bank-sim/payouts/<int:payout_id>/status/",
        UpdateBankSimulatorPayoutStatusView.as_view(),
        name="bank-sim-status-update",
    ),
    path("reconciliation/summary/", ReconciliationSummaryView.as_view(), name="reconciliation-summary"),
]
