# Generated by Django 5.1.5 on 2026-03-18 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driverfleetmembership'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='accounts.fleet'),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('user_wallet', 'User Wallet'), ('driver_available', 'Driver Available'), ('fleet_reserve', 'Fleet Reserve'), ('treasury', 'Treasury'), ('platform_fee', 'Platform Fee'), ('system', 'System')], default='user_wallet', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'account_type', 'currency'), name='ledger_unique_user_type_currency'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('fleet__isnull', False), ('user__isnull', True)), fields=('fleet', 'account_type', 'currency'), name='ledger_unique_fleet_type_currency'),
        ),
    ]
