# Generated by Django 5.1.5 on 2026-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgeraccount_fleet_alter_ledgeraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('user_wallet', 'User Wallet'), ('driver_available', 'Driver Available'), ('fleet_reserve', 'Fleet Reserve'), ('treasury', 'Treasury'), ('platform_fee', 'Platform Fee'), ('payout_clearing', 'Payout Clearing'), ('system', 'System')], default='user_wallet', max_length=20),
        ),
    ]
